name: student_questionnaire
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  csv: ^5.1.1
  excel: ^4.0.6
  file_picker: ^8.0.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  intl: ^0.18.0
  firebase_auth: ^5.5.2
  provider: ^6.1.4
  shared_preferences: ^2.2.0
  printing: ^5.10.7
  pdf: ^3.11.3
  fl_chart: ^0.71.0
  file_saver: ^0.2.14
  syncfusion_flutter_xlsio: ^24.2.9
  internet_connection_checker: ^3.0.1
  connectivity_plus: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/ 
    - assets/icon/


    